# Adding Clusters, Regions to the intermediate dataset

In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
data = pd.read_csv("finaldata.csv")

In [3]:
clusresult = pd.read_csv("cluster results.csv")

## Understanding and checking for any data problems

In [4]:
clusresult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  350 non-null    int64
 1   STATE                       350 non-null    object
 2   Year                        350 non-null    int64
 3   CO2                         350 non-null    int64
 4   CH4                         350 non-null    int64
 5   N2O                         350 non-null    int64
 6   Fluorinated GHG             112 non-null    float64
 7   Laws and Regulations        350 non-null    int64
 8   State Incentives            350 non-null    int64
 9   Utility/Private Incentives  350 non-null    int64
 10  Ozone                       350 non-null    float64
 11  cluster                     350 non-null    int64
dtypes: float64(2), int64(9), object(1)
memory usage: 32.9+ KB

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22468 entries, 0 to 22467
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  22468 non-null  int64
 1   STATE                       22468 non-null  object
 2   Year                        22468 non-null  int64
 3   CO2                         22468 non-null  int64
 4   CH4                         22468 non-null  int64
 5   N2O                         22468 non-null  int64
 6   Fluorinated GHG             22468 non-null  int64
 7   Laws and Regulations        22468 non-null  int64
 8   State Incentives            22468 non-null  int64
 9   Utility/Private Incentives  22468 non-null  int64
 10  Ozone                       22468 non-null  float64
 11  Question                    22416 non-null  object
 12  DataValue                   17119 non-null  float64
 13  StratificationCategory1     22416 non-null  object
 14  Stratification1             22416 non-null  object
 15  Population                  22468 non-null  float64
 16  Total Sq. Mi.               22468 non-null  object
 17  Total Sq. Km.               22468 non-null  object
dtypes: float64(3), int64(9), object(6)
memory usage: 3.1+ MB

In [6]:
clusresult[50:100]

,Unnamed: 0,STATE,Year,CO2,CH4,N2O,Fluorinated GHG,Laws and Regulations,State Incentives,Utility/Private Incentives,Ozone,cluster
50,50,DE,2013,7932200,320105,16742,NaN,4,9,5,0.042863,1
51,51,DE,2014,7798501,374321,13222,NaN,3,9,5,0.043434,1
52,52,DE,2015,7547438,502657,13336,NaN,3,9,4,0.045131,1
53,53,DE,2016,7832062,496746,14045,NaN,3,8,4,0.044544,1
54,54,DE,2017,6560049,488161,10194,NaN,3,7,4,0.042460,1
55,55,DE,2018,6578229,439430,11025,NaN,3,7,3,0.040939,1
56,56,FL,2012,120645361,6901194,5739976,NaN,15,7,9,0.037726,2
57,57,FL,2013,118084663,6606354,4501029,NaN,15,8,9,0.036521,2
58,58,FL,2014,123269319,6671539,4994554,NaN,14,8,9,0.038533,2
59,59,FL,2015,122278676,6564558,4080300,NaN,14,8,9,0.035945,2
60,60,FL,2016,119934078,6872800,7524030,NaN,14,7,7,0.037794,2
61,61,FL,2017,117113291,7406817,7748239,NaN,14,7,7,0.037094,2
62,62,FL,2018,114676444,7754614,10807191,NaN,15,7,6,0.036470,2
63,63,GA,2012,68712277,5475353,974012,NaN,6,9,5,0.044242,0
64,64,GA,2013,66860223,5792625,943831,NaN,6,9,4,0.039603,0
65,65,GA,2014,72214155,5910259,891464,NaN,5,10,4,0.041431,0
66,66,GA,2015,67822919,5762788,806210,NaN,6,7,4,0.039999,0
67,67,GA,2016,68832714,5629746,955746,NaN,6,7,3,0.044348,0
68,68,GA,2017,62295847,5561195,835107,NaN,6,6,3,0.040242,0
69,69,GA,2018,62615237,6035282,646851,NaN,6,5,3,0.039748,0
70,70,HI,2012,9002385,449058,34707,NaN,16,3,3,0.026813,1
71,71,HI,2013,8433448,402093,36760,NaN,16,3,3,0.029167,1
72,72,HI,2014,8618319,389865,34955,NaN,15,3,3,0.027041,1
73,73,HI,2015,8476439,389086,34235,NaN,15,3,3,0.028106,1
74,74,HI,2016,8307413,328296,34096,NaN,15,3,3,0.029220,1
75,75,HI,2017,7831066,329809,29164,NaN,15,3,3,0.029274,1
76,76,HI,2018,7853288,356888,31101,NaN,14,3,3,0.029367,1
77,77,ID,2012,3224664,439437,28062,52716.0,6,4,2,0.049922,1
78,78,ID,2013,4121630,595299,13106,41443.0,6,5,2,0.045410,1
79,79,ID,2014,3598793,568566,11635,38633.0,6,5,2,0.048538,1
80,80,ID,2015,4189643,657680,11526,53311.0,8,5,2,0.047661,1
81,81,ID,2016,3905882,613376,10402,67836.0,8,5,2,0.047442,1
82,82,ID,2017,3790158,595248,9578,45753.0,9,5,2,0.045963,1
83,83,ID,2018,3762251,563705,9705,50669.0,8,5,2,0.040651,1
84,84,IL,2012,120217587,7788190,666095,1766538.0,20,18,3,0.047488,0
85,85,IL,2013,122960612,8092836,654057,2479664.0,22,18,2,0.041958,0
86,86,IL,2014,121941962,7980578,529376,1465387.0,19,19,2,0.041747,0
87,87,IL,2015,109192848,9270514,481262,1092957.0,19,19,2,0.041979,0
88,88,IL,2016,96390512,9130575,407616,868370.0,19,17,2,0.042858,0
89,89,IL,2017,93157350,7332914,392019,946365.0,20,13,1,0.043428,0
90,90,IL,2018,97792906,6476368,506608,935118.0,18,12,1,0.042618,0
91,91,IN,2012,148643197,6469836,651622,200140.0,13,17,5,0.049292,0
92,92,IN,2013,149530450,6500050,508009,203444.0,16,21,5,0.044383,0
93,93,IN,2014,153565562,6450999,523286,303211.0,15,19,5,0.043503,0
94,94,IN,2015,135228766,6595353,435616,289834.0,14,15,5,0.042296,0
95,95,IN,2016,132281876,5929805,409760,253087.0,14,12,5,0.043927,0
96,96,IN,2017,131660934,5848882,396793,180607.0,16,12,3,0.042524,0
97,97,IN,2018,139107023,6020561,422149,281807.0,16,12,2,0.041615,0
98,98,IA,2012,53709131,1766165,1171230,NaN,10,10,6,0.046630,1
99,99,IA,2013,51815222,1626488,1008033,NaN,10,9,6,0.041200,1

## Dropping unwanted columns

In [18]:

df = clusresult.drop(columns=['Unnamed: 0','CO2','CH4','N2O','Fluorinated GHG','Laws and Regulations','State Incentives','Utility/Private Incentives',
                              'Ozone'])

In [19]:
df.head()

  STATE  Year  cluster
0    AL  2012        1
1    AL  2013        1
2    AL  2014        1
3    AL  2015        1
4    AL  2016        1

In [21]:
data[150:200]

,STATE,Year,CO2,CH4,N2O,Fluorinated GHG,Laws and Regulations,State Incentives,Utility/Private Incentives,Ozone,Question,DataValue,StratificationCategory1,Stratification1,Population,Total Sq. Mi.,Total Sq. Km.
150,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,208.9,Gender,Female,4841799.0,"52,420","135,767"
151,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
152,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,112.0,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
153,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,135.3,Gender,Female,4841799.0,"52,420","135,767"
154,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
155,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,268.9,Gender,Male,4841799.0,"52,420","135,767"
156,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,145.6,Overall,Overall,4841799.0,"52,420","135,767"
157,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,11.8,Overall,Overall,4841799.0,"52,420","135,767"
158,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,157.5,Gender,Male,4841799.0,"52,420","135,767"
159,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
160,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
161,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
162,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,290.5,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
163,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,349.2,Gender,Male,4841799.0,"52,420","135,767"
164,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
165,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,80.2,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
166,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,142.4,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767"
167,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,11.0,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
168,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,92.6,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
169,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
170,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,334.6,Overall,Overall,4841799.0,"52,420","135,767"
171,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,95.2,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
172,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,321.0,Gender,Female,4841799.0,"52,420","135,767"
173,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,124.9,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767"
174,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,257.0,Overall,Overall,4841799.0,"52,420","135,767"
175,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,377.9,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767"
176,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
177,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,275.0,Gender,Male,4841799.0,"52,420","135,767"
178,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,117.2,Gender,Male,4841799.0,"52,420","135,767"
179,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,211.6,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
180,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
181,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,115.6,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"
182,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,106.1,Overall,Overall,4841799.0,"52,420","135,767"
183,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,294.8,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767"
184,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,121.2,Overall,Overall,4841799.0,"52,420","135,767"
185,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
186,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
187,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,12.5,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
188,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,44.4,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
189,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,125.3,Gender,Male,4841799.0,"52,420","135,767"
190,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,32.8,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
191,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,125.1,Gender,Female,4841799.0,"52,420","135,767"
192,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,240.0,Gender,Female,4841799.0,"52,420","135,767"
193,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,1084.0,Gender,Male,4841799.0,"52,420","135,767"
194,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767"
195,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,870.4,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767"
196,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,283.4,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767"
197,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,882.7,Overall,Overall,4841799.0,"52,420","135,767"
198,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,1014.4,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767"
199,AL,2014,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,357.9,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767"

In [22]:
df_final = pd.merge(
                     
                     df,data,
                     how  = 'left', on = ['STATE','Year'])

In [23]:
df_final.head()

,STATE,Year,cluster,CO2,CH4,N2O,Fluorinated GHG,Laws and Regulations,State Incentives,Utility/Private Incentives,Ozone,Question,DataValue,StratificationCategory1,Stratification1,Population,Total Sq. Mi.,Total Sq. Km.
0,AL,2012,1,84138381,701702,602778,264437,3,7,4,0.044215,Mortality from diseases of the heart,234.8,Gender,Female,4815588.0,"52,420","135,767"
1,AL,2012,1,84138381,701702,602778,264437,3,7,4,0.044215,Asthma mortality rate,14.9,Gender,Female,4815588.0,"52,420","135,767"
2,AL,2012,1,84138381,701702,602778,264437,3,7,4,0.044215,Asthma mortality rate,8.6,Gender,Male,4815588.0,"52,420","135,767"
3,AL,2012,1,84138381,701702,602778,264437,3,7,4,0.044215,Asthma mortality rate,8.9,Race/Ethnicity,"White, non-Hispanic",4815588.0,"52,420","135,767"
4,AL,2012,1,84138381,701702,602778,264437,3,7,4,0.044215,Asthma mortality rate,21.8,Race/Ethnicity,"Black, non-Hispanic",4815588.0,"52,420","135,767"

## Reading State data containing region number and name

In [24]:
division = pd.read_csv("statdata.csv")

In [25]:
division.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   REGION       51 non-null     int64
 1   STATE        51 non-null     object
 2   Region_Name  51 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.3+ KB

In [26]:
division[1:15]

    REGION STATE       Region_Name
1        4    AK       West Region
2        4    AZ       West Region
3        3    AR      South Region
4        4    CA       West Region
5        4    CO       West Region
6        1    CT  Northeast Region
7        3    DE      South Region
8        3    DC      South Region
9        3    FL      South Region
10       3    GA      South Region
11       4    HI       West Region
12       4    ID       West Region
13       2    IL    Midwest Region
14       2    IN    Midwest Region

In [27]:
df_final = pd.merge(
                     
                     df_final,division,
                     how  = 'left', on = ['STATE'])

In [28]:
df_final[150:200]

,STATE,Year,cluster,CO2,CH4,N2O,Fluorinated GHG,Laws and Regulations,State Incentives,Utility/Private Incentives,Ozone,Question,DataValue,StratificationCategory1,Stratification1,Population,Total Sq. Mi.,Total Sq. Km.,REGION,Region_Name
150,AL,2013,1,83297945,594388,451420,274194,3,7,4,0.039733,"Cancer of the lung and bronchus, incidence",67.0,Gender,Female,4830081.0,"52,420","135,767",3,South Region
151,AL,2013,1,83297945,594388,451420,274194,3,7,4,0.039733,"Cancer of the lung and bronchus, incidence",82.3,Overall,Overall,4830081.0,"52,420","135,767",3,South Region
152,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,36.9,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767",3,South Region
153,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,88.1,Gender,Female,4841799.0,"52,420","135,767",3,South Region
154,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Premature mortality among adults aged 45-64 years,695.8,Gender,Female,4841799.0,"52,420","135,767",3,South Region
155,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,176.8,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
156,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
157,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,59.6,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
158,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,9.4,Gender,Male,4841799.0,"52,420","135,767",3,South Region
159,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,14.0,Gender,Female,4841799.0,"52,420","135,767",3,South Region
160,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,8.6,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
161,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,NaN,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767",3,South Region
162,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,282.6,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
163,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,21.5,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
164,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767",3,South Region
165,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,236.7,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
166,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,208.9,Gender,Female,4841799.0,"52,420","135,767",3,South Region
167,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767",3,South Region
168,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,112.0,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
169,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,135.3,Gender,Female,4841799.0,"52,420","135,767",3,South Region
170,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767",3,South Region
171,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,268.9,Gender,Male,4841799.0,"52,420","135,767",3,South Region
172,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,145.6,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
173,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Asthma mortality rate,11.8,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
174,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,157.5,Gender,Male,4841799.0,"52,420","135,767",3,South Region
175,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
176,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767",3,South Region
177,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality with chronic obstructive pulmonary d...,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
178,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,290.5,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
179,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,349.2,Gender,Male,4841799.0,"52,420","135,767",3,South Region
180,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767",3,South Region
181,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,80.2,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
182,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,142.4,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
183,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,11.0,Race/Ethnicity,Hispanic,4841799.0,"52,420","135,767",3,South Region
184,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,92.6,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
185,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
186,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,334.6,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
187,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,95.2,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
188,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,321.0,Gender,Female,4841799.0,"52,420","135,767",3,South Region
189,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,124.9,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
190,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,257.0,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
191,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,377.9,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
192,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,NaN,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
193,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,275.0,Gender,Male,4841799.0,"52,420","135,767",3,South Region
194,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from heart failure,117.2,Gender,Male,4841799.0,"52,420","135,767",3,South Region
195,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,211.6,Race/Ethnicity,"Black, non-Hispanic",4841799.0,"52,420","135,767",3,South Region
196,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,NaN,Race/Ethnicity,Asian or Pacific Islander,4841799.0,"52,420","135,767",3,South Region
197,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from total cardiovascular diseases,115.6,Race/Ethnicity,American Indian or Alaska Native,4841799.0,"52,420","135,767",3,South Region
198,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from coronary heart disease,106.1,Overall,Overall,4841799.0,"52,420","135,767",3,South Region
199,AL,2014,1,84847355,634009,525399,312201,3,7,4,0.040936,Mortality from diseases of the heart,294.8,Race/Ethnicity,"White, non-Hispanic",4841799.0,"52,420","135,767",3,South Region

## Creating merged dataset file from the python notebook

In [81]:
df_final.to_csv('finaldata_clusters_regions_Added.csv')